### ISSUE TITLE
Netgear R7000 doesnt respond after receiving the firmware

### ISSUE THREAD

**Issue by palealibi** [jclehner/nmrpflash#129]
tried several firmwares, same issue

D:\>nmrpflash -i net27 -f R7000-V1.0.0.96_1.0.15.chk
Waiting for Ethernet connection (Ctrl-C to skip).
Advertising NMRP server on net27 ... /
Received configuration request from 00:46:bc:8d:5e:71.
Sending configuration: 10.164.183.253/24.
Received upload request without filename.
Uploading R7000-V1.0.0.96_1.0.15.chk ... OK (17772602 b)
Waiting for remote to respond.
Received configuration request from 00:46:bc:8d:5e:71.
Sending configuration: 10.164.183.253/24.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:46:bc:8d:5e:71.
Sending configuration: 10.164.183.253/24.

**Comment by jclehner** [comment]
This could be due to the firmware checking the version number, and refusing a downgrade, or reinstallation of the same version. You can use my [patchchk](https://github.com/jclehner/patchchk/releases/tag/v3) tool to adjust the version number of a firmware image.

**Comment by jclehner** [comment]
Also, try this version instead: 
[nmrpflash-0.9.20-7-g493270f-win32.zip](https://github.com/jclehner/nmrpflash/files/12174415/nmrpflash-0.9.20-7-g493270f-win32.zip)

**Comment by ljy1812** [comment]
Same issue here. May write the wrong cef file into, got the wrong mac address. Don't know if it is the reason. Did anyone know how to fix the problem? I can not connect to the router using putty telnet, so I can rewrite the cef. I can use the Netgear web gui, but  can't update any firmware by the gui. Just said "invalid firmware ".  And I can't using other tftp client to update the firmware too. The nmrpflash is the only way to connect and upload the file, but seems failed to flash the file to the router. 


Advertising NMRP server on net19 ... \
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Received upload request without filename.
Uploading factory-to-dd-wrt.chk ... OK (28127290 b)
Waiting for remote to respond.
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.

**Comment by jclehner** [comment]
This issue should be fixed in the latest development version (not yet released). Please try this, and post the output again (run nmrpflash with `-vv`):

[nmrpflash-0.9.20-13-g6f6f570-win32.zip](https://github.com/jclehner/nmrpflash/files/12284958/nmrpflash-0.9.20-13-g6f6f570-win32.zip)

**Comment by ljy1812** [comment]
Thank you very much. I have tried and here is the output. I am able to enter into the busybox system of the r7000 using putty telnet. But still don't know how to write the backup CFE file in.  The r7000 router function is all good, my phone can connect to r7000 and get to internet. But when I try to check the firmware update (on Netgear web GUI), it said no internet connection. 


C:\Users\lenovo\Downloads\r7000>nmrpflash.exe -vv -i net2 -f factory-to-dd-wrt.chk
Waiting for Ethernet connection (Ctrl-C to skip).
Adding 10.164.183.252 to interface net2.
Advertising NMRP server on net2 ... /
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Received upload request without filename.
Using remote filename 'factory-to-dd-wrt.chk'.
Uploading factory-to-dd-wrt.chk ... Drained 0 packet(s) from rx buffer
OK (28127290 b)
Waiting for remote to respond.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.

**Comment by jclehner** [comment]
The "Ignoring extra upload request." message usually indicates that the device rejected the firmware file. This issue could be related to the version number of your ` factory-to-dd-wrt.chk` being lower than the version of the currently installed firmware.

You can try my [patchchk](https://github.com/jclehner/patchchk) tool to update the version number of a `.chk` file.

**Comment by ljy1812** [comment]
Thank you for the reply. I have tried the newer version of chk file of R7000-V1.0.4.18_1.1.52.chk. The current firmware version of the r7000 is 1.0.3.80_1.1.38. And I got the same resultes show as the below. Get it run more than 30 minutes. I will try the patchchk to update the version of dd-wrt chk file later to see if I get any luck. 

C:\Users\lenovo\Downloads\r7000>nmrpflash.exe -vv -i net2 -f R7000-V1.0.4.18_1.1.52.chk
Waiting for Ethernet connection (Ctrl-C to skip).
Adding 10.164.183.252 to interface net2.
Advertising NMRP server on net2 ... |
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Received upload request without filename.
Using remote filename 'R7000-V1.0.4.18_1.1.52.chk'.
Uploading R7000-V1.0.4.18_1.1.52.chk ... Drained 0 packet(s) from rx buffer
OK (27566138 b)
Waiting for remote to respond.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:31:f0:d2:5b:fc.
Sending configuration: 10.164.183.253/24.
Ignoring extra upload request.
Ignoring extra upload request.

**Comment by ljy1812** [comment]
I finally can update the r7000 firmware by web browser. Please check here, https://www.linksysinfo.org/index.php?threads/asuswrt-merlin-on-netgear-r7000.71108/
visit the "Unbrick tutorial by [@User0815](https://www.linksysinfo.org/index.php?members/63731/) in case of stuck on the ofw is [here](https://www.linksysinfo.org/index.php?threads/asuswrt-merlin-on-netgear-r7000.71108/page-269#post-295716).". following the stps, burnboardid and reboot. Them you can update the firmare by web browser.

**Comment by ljy1812** [comment]
One error forgot to mention, The command should be "burnboardid U12H270T00_NETGEAR", has the "_" between.
